language: r
sudo: required
dist: trusty

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

notifications:
  email:
    on_success: change
    on_failure: change

r:
  - release
  - devel
  - oldrel
