language: r
sudo: required
dist: trusty

r_build_args: --no-build-vignettes
r_check_args: --no-build-vignettes

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

r:
  - release
  - devel
  - oldrel
  
matrix:
  allow_failures:
    - r: devel

notifications:
  email:
    on_success: change
    on_failure: change
