language: r
sudo: required
dist: trusty

r_build_args: --no-build-vignettes
r_check_args: --no-build-vignettes

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libgdal-dev
      - libproj-dev

r:
  - release
  - devel
  - oldrel

notifications:
  email:
    on_success: change
    on_failure: change
